### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by chupocro** [ewenchou/alexa-client#10]
**EDIT:**
This is in fact Alexa **agent** issue. I posted it here by mistake.

When I run:

`alexa-agent/examples $ python what_time_is_it.py`

there is an error:

```
alexa-agent/examples $ python what_time_is_it.py
Traceback (most recent call last):
  File "what_time_is_it.py", line 11, in <module>
    main()
  File "what_time_is_it.py", line 6, in main
    agent.wakeup()
  File "/usr/local/lib/python2.7/dist-packages/alexa_agent-0.1-py2.7.egg/alexa_agent/agent.py", line 17, in wakeup
    self.play_mp3("{}/wakeup.mp3".format(self.audio_dir))
  File "/usr/local/lib/python2.7/dist-packages/alexa_agent-0.1-py2.7.egg/alexa_agent/agent.py", line 94, in play_mp3
    p = subprocess.Popen(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by chupocro** [comment]
The solution is to install `mpg123`:

`sudo apt-get install mpg123`
