### ISSUE TITLE
Key Error When running auth_web.py

### ISSUE THREAD

**Issue by hankp46** [ewenchou/alexa-client#11]
When attempting to run auth_web.py I get following error:
python auth_web.py -d
Traceback (most recent call last):
  File "auth_web.py", line 2, in <module>
    from alexa_client.settings import PRODUCT_ID, CLIENT_ID, CLIENT_SECRET, WEB_PORT
  File "/home/pi/alexa-client/alexa_client/__init__.py", line 1, in <module>
    from alexa_client import AlexaClient
  File "/home/pi/alexa-client/alexa_client/alexa_client.py", line 8, in <module>
    import settings
  File "/home/pi/alexa-client/alexa_client/settings.py", line 4, in <module>
    CLIENT_ID = os.environ['amzn1.application-oa2-client.xxxxxxxxxxxxxxxx']]
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'amzn1.application-oa2-client.xxxxxxxxxxxxxx'

Have no idea where to go next.

**Comment by paulpall** [comment]
Did you generate your own keys? If so, try removing the "os.environ[" (along with the closing bracket) in settings.py!
