### ISSUE TITLE
auth_web.py issue when try to get Authorization Code Grant

### ISSUE THREAD

**Issue by davideferrari95** [ewenchou/alexa-client#12]
Hi, I am trying to follow your setup guide for Alexa Client and I get stuck in the request for the Authorization Code Grant.
I have successfully created a new "AVS Product" and I linked it with a “Security Profiles”. 
I added the "Allowed Origins" and "Return URLs" to Web Settings tab in Security Profile and i get from that the `CLIENT_ID` and `CLIENT_SECRET`.

`CLIENT_ID` = amzn1.application-oa2-client.e3102***************************
`PRODUCT_ID` is the ID I have set when I have created the AVS Product ?

Now, following the Readme, I have to lauch from terminal:
```
python auth_web.py
```
But I get the following message:

```
Traceback (most recent call last):
  File "auth_web.py", line 2, in <module>
    from alexa_client.settings import PRODUCT_ID, CLIENT_ID, CLIENT_SECRET, WEB_PORT
  File "/home/davide/davide_ws/src/Speech_Recogn/alexa-client/alexa_client/__init__.py", line 1, in <module>
    from alexa_client import AlexaClient
  File "/home/davide/davide_ws/src/Speech_Recogn/alexa-client/alexa_client/alexa_client.py", line 8, in <module>
    import settings
  File "/home/davide/davide_ws/src/Speech_Recogn/alexa-client/alexa_client/settings.py", line 3, in <module>
    CLIENT_ID = os.environ['amzn1.application-oa2-client.e3102***************************'] #ALEXA_CLIENT_ID
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'amzn1.application-oa2-client.e3102***************************'
```

**Comment by davideferrari95** [comment]
> 
> 
> Hi, I am trying to follow your setup guide for Alexa Client and I get stuck in the request for the Authorization Code Grant.
> I have successfully created a new "AVS Product" and I linked it with a “Security Profiles”.
> I added the "Allowed Origins" and "Return URLs" to Web Settings tab in Security Profile and i get from that the CLIENT_ID and CLIENT_SECRET.
> 
> CLIENT_ID = amzn1.application-oa2-client.e3102***************************
> PRODUCT_ID is the ID I have set when I have created the AVS Product ?
> 
> Now, following the Readme, I have to lauch from terminal:
> 
> ```
> python auth_web.py
> ```
> 
> But I get the following message:
> 
> ```
> Traceback (most recent call last):
>   File "auth_web.py", line 2, in <module>
>     from alexa_client.settings import PRODUCT_ID, CLIENT_ID, CLIENT_SECRET, WEB_PORT
>   File "/home/davide/davide_ws/src/Speech_Recogn/alexa-client/alexa_client/__init__.py", line 1, in <module>
>     from alexa_client import AlexaClient
>   File "/home/davide/davide_ws/src/Speech_Recogn/alexa-client/alexa_client/alexa_client.py", line 8, in <module>
>     import settings
>   File "/home/davide/davide_ws/src/Speech_Recogn/alexa-client/alexa_client/settings.py", line 3, in <module>
>     CLIENT_ID = os.environ['amzn1.application-oa2-client.e3102***************************'] #ALEXA_CLIENT_ID
>   File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
>     raise KeyError(key)
> KeyError: 'amzn1.application-oa2-client.e3102***************************'
> ```

I tried to change the `settings.py` file and now I can run the script; I remove the `os.environ` and it works:

```
CLIENT_ID = 'ALEXA_CLIENT_ID'
CLIENT_SECRET = 'ALEXA_CLIENT_SECRET'
PRODUCT_ID = 'ALEXA_PRODUCT_ID'
REFRESH_TOKEN = 'ALEXA_REFRESH_TOKEN'
WEB_PORT = 3000
```

Is it correct ? I miss something about `os.environ` ?
