### ISSUE TITLE
Key error with access token

### ISSUE THREAD

**Issue by ibaranov-cp** [ewenchou/alexa-client#3]
Hello,

I have followed the setup steps, and input client_id, client secret. For token, I used the generated token given by amazon's java client in the guide you linked (perhaps this is not the right token?)

However, I get this:

```
Traceback (most recent call last):
  File "test/test_ask.py", line 18, in <module>
    main()
  File "test/test_ask.py", line 13, in main
    alexa.ask(input, save_to=save_to)
  File "/usr/local/lib/python2.7/dist-packages/alexa_client-0.5-py2.7.egg/alexa_client/alexa_client.py", line 137, in ask
    url, headers, request_data = self.get_request_params()
  File "/usr/local/lib/python2.7/dist-packages/alexa_client-0.5-py2.7.egg/alexa_client/alexa_client.py", line 68, in get_request_params
    headers = {'Authorization' : 'Bearer %s' % self.get_token()}
  File "/usr/local/lib/python2.7/dist-packages/alexa_client-0.5-py2.7.egg/alexa_client/alexa_client.py", line 51, in get_token
    self._token = res_json['access_token']
KeyError: 'access_token'
```

**Comment by ewenchou** [comment]
You need to follow the instructions from [this Amazon guide](https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/docs/authorizing-your-alexa-enabled-product-from-a-website) to do an "Authorization Code Grant". This will give you both an access token and a refresh token. That way you don't need to reauthorize your device every half hour or so.

**Comment by ewenchou** [comment]
I've updated the repo with `auth_web.py` script and information in the README on how to get the refresh token. Hope it helps :)

**Comment by ibaranov-cp** [comment]
That is awesome, thank you! :+1:
