### ISSUE TITLE
AVS not accepting new refresh token

### ISSUE THREAD

**Issue by cbolles** [ewenchou/alexa-client#9]
I have been using the client for a while now with no issue, today I attempt to call the same test_ask as I have been using and I get the response 

`AVS returned error: Status: 403, Text: {"error":{"code":"com.amazon.alexahttpproxy.exceptions.InvalidAccessTokenException","message":"AVS was not able to validate the provided access token."}}
Traceback (most recent call last):
  File "test_ask.py", line 18, in <module>
    main()
  File "test_ask.py", line 13, in main
    alexa.ask(input, save_to=save_to)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/alexa_client-0.5-py2.7.egg/alexa_client/alexa_client.py", line 159, in ask
    return self.save_response_audio(res, save_to)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/alexa_client-0.5-py2.7.egg/alexa_client/alexa_client.py", line 123, in save_response_audio
    res.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://access-alexa-na.amazon.com/v1/avs/speechrecognizer/recognize`

I generated a new refresh token using the auth_web.py script, updated the settings, and reran setup.py. I still get the error from above. I am fairly certain I am following the steps exactly the same, the client_secret, and client_id are definitely correct.

macOS: High Sierrra 10.13.2
python: 2.7.13

**Comment by cbolles** [comment]
Maybe the issue was AVS authentication not functioning that day, made no changes and ran the same code again and got a successful Alexa response.
